name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Say Hello Someone it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
      - name: "this is the name of the step"
        run: echo "${{ github.job }} is the name of the job. Or maybe it's the ID."
