name: If statement test 2.0

on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - run: echo 'Hello, world!'
        - run: echo 'Hello, warld!'
    statement-if:
        runs-on: ubuntu-latest
        if: ${{ !startsWith(github.ref, 'refs/heads/test') && github.event_name == 'push' }}
        steps:
        - run: echo 'Summer!'
