name: Image Optimizer

on:
  push:
    paths:
      - 'images/**'  # Path to images

jobs:
  optimize-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Optimize Images
        run: npx imagemin images/** --out-dir=optimized-images
